default: &default
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: adela_development
  host: localhost

test:
  <<: *default
  database: adela_test

staging:
  <<: *default
  database: adela_staging
  username: postgres
  host: postgres
  password:

production:
  <<: *default
  database: adela_production
  username: postgres
  host: postgres
  password:
