default: &default
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: adela_development

test:
  <<: *default
  database: adela_test

production:
  <<: *default
  database: adela_production
  username: postgres
  host: postgres
  password:
