common: &default_settings
  license_key: <%= ENV['NEWRELIC_LICENSE_KEY'] %>
  app_name: adela
  log_level: info

development:
  <<: *default_settings
  app_name: adela (Development)
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
